service: hello-world-service
app: graphql-servierless-boilerplate
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  stage: ${opt:stage, env:SLS_STAGE, 'local'}
  environment:
    REGION: ${self:provider.region}
    ENV: ${self:provider.stage}

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpackConfig: './webpack.config.js' # Name of webpack configuration file
  webpackIncludeModules: true # Node modules configuration for packaging
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      heapInitial: 200m
      heapMax: 1g
      convertEmptyValues: true
    seed:
      domain:
        sources:
          - table: HelloWorld
            sources: [./seed-data/hello-world.json]

functions:
  graphql:
    handler: ./src/handler.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: ./src/playground.handler
    events:
      - http:
          method: get
          path: playground

resources:
  Resources:
    HelloWorldTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: 'HelloWorld'
