service: hello-world-service
app: graphql-servierless-boilerplate
provider:
  name: aws
  runtime: nodejs8.10
#  region: YOUR_REGION
  stage: dev
  environment: 
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
plugins:
    - serverless-offline
    - serverless-webpack
    - serverless-dynamodb-local

custom:
  webpackConfig: './webpack.config.js'   # Name of webpack configuration file
  includeModules: true   # Node modules configuration for packaging
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
        - table: HelloWorld
          sources: [./seed-data/hello-world.json]

functions:
  graphql:
    handler: ./src/handler.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: ./src/handler.handler
    events:
      - http:
          path: playground
          method: get

resources:
  Resources:
    HelloWorldTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: 'HelloWorld'

