service: hello-world-service
app: graphql-servierless-boilerplate
provider:
  name: aws
  runtime: nodejs8.10
#  region: YOUR_REGION
  stage: dev
plugins:
    - serverless-offline
    - serverless-webpack

custom:
  webpackConfig: './webpack.config.js'   # Name of webpack configuration file
  includeModules: true   # Node modules configuration for packaging

functions:
  graphql:
    handler: ./src/handler.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: ./src/handler.handler
    events:
      - http:
          path: playground
          method: get


